### ISSUE TITLE
pgnextractor creates invalid json

### ISSUE THREAD

**Issue by gbtami** [sshivaji/pgnextractor#2]
The output should be a Python list of dicts like [{first game headers}, {second game headers}, ... ,{last game headers}]
It now produces Python dicts per game without wrapping them into a list.

**Comment by sshivaji** [comment]
It is a JSON per line, if we did a gigantic JSON, it would be slow to load, is a JSON per line too much of a limitation?

**Comment by gbtami** [comment]
I'm fine with one JSON per line just was expecting .json will be one big JSON by readme .
