### ISSUE TITLE
FEN not extracted to .json

### ISSUE THREAD

**Issue by gbtami** [sshivaji/pgnextractor#4]
[Event "Live Chess"]
[Site "Chess.com"]
[Date "2016.10.27"]
[Round "-"]
[White "Hikaru"]
[Black "MagnusCarlsen"]
[Result "1-0"]
[Variant "Chess960"]
[SetUp "1"]
[FEN "nqrkbbrn/pppppppp/8/8/8/8/PPPPPPPP/NQRKBBRN w GCgc - 0 1"]
[WhiteElo "3025"]
[BlackElo "2692"]
[TimeControl "300+2"]
[Termination "Hikaru won by resignation"]

1. c4 {[%clk 0:04:57]} 1... Ng6 {[%clk 0:04:51]} 2. f4 {[%clk 0:04:47]} 2... c5
{[%clk 0:04:39]} 3. g3 {[%clk 0:04:35]} 3... e6 {[%clk 0:04:38]} 4. Bg2 {[%clk
0:04:27]} 4... Nb6 {[%clk 0:04:34]} 5. Nb3 {[%clk 0:04:25]} 5... d5 {[%clk
0:04:28]} 6. cxd5 {[%clk 0:04:00]} 6... exd5 {[%clk 0:04:29]} 7. Bf2 {[%clk
0:03:40]} 7... d4 {[%clk 0:04:30]} 8. O-O {[%clk 0:03:35]} 8... Be7 {[%clk
0:04:18]} 9. Qf5 {[%clk 0:03:21]} 9... Qd6 {[%clk 0:03:06]} 10. Na5 {[%clk
0:03:18]} 10... Rc7 {[%clk 0:03:07]} 11. b4 {[%clk 0:02:51]} 11... c4 {[%clk
0:03:00]} 12. Nxb7+ {[%clk 0:02:51]} 12... Rxb7 {[%clk 0:03:01]} 13. Bxb7 {[%clk
0:02:53]} 13... Bd7 {[%clk 0:03:03]} 14. Qe4 {[%clk 0:02:39]} 14... Bf6 {[%clk
0:03:04]} 15. Qg2 {[%clk 0:01:49]} 15... Re8 {[%clk 0:03:01]} 16. e4 {[%clk
0:01:47]} 16... dxe3 {[%clk 0:02:51]} 17. dxe3 {[%clk 0:01:47]} 17... Qxb4
{[%clk 0:02:53]} 18. Bc6 {[%clk 0:01:33]} 18... c3 {[%clk 0:02:40]} 19. Rfd1
{[%clk 0:01:30]} 19... Kc7 {[%clk 0:02:22]} 20. Bxd7 {[%clk 0:01:31]} 20... Nxd7
{[%clk 0:02:24]} 21. g4 {[%clk 0:01:31]} 21... h6 {[%clk 0:02:22]} 22. Ng3
{[%clk 0:01:27]} 22... Nb6 {[%clk 0:02:16]} 23. Nh5 {[%clk 0:01:25]} 23... Nh4
{[%clk 0:02:08]} 24. Bxh4 {[%clk 0:01:06]} 24... Bxh4 {[%clk 0:02:10]} 25. Qd2
{[%clk 0:01:07]} 25... Kb7 {[%clk 0:01:55]} 26. Qxc3 {[%clk 0:01:05]} 26... Qe4
{[%clk 0:01:52]} 27. Qc7+ {[%clk 0:01:05]} 27... Ka8 {[%clk 0:01:53]} 28. Qc6+
{[%clk 0:01:04]} 28... Qxc6 {[%clk 0:01:54]} 29. Rxc6 {[%clk 0:01:06]} 29... Kb7
{[%clk 0:01:52]} 30. Nxg7 {[%clk 0:00:53]} 1-0

{"Event": "Live Chess", "Site": "Chess.com", "Date": "2016.10.27", "Round": "-", "White": "Hikaru", "Black": "MagnusCarlsen", "Result": "1-0", "Variant": "Chess960", "Event": "Live Chess", "Site": "Chess.com", "Date": "2016.10.27", "Round": "-", "White": "MagnusCarlsen", "Black": "Hikaru", "Result": "1-0", "WhiteElo": "2871", "BlackElo": "2959", "TimeControl": "300+2", "Termination": "MagnusCarlsen won by resignation", "offset":22846,"offset_8":182768}

**Comment by sshivaji** [comment]
What is the exact problem above, why is this not valid JSON?

**Comment by gbtami** [comment]
It's valid but FEN is missing.

**Comment by sshivaji** [comment]
Sorry for the late replies. Got busy in the middle. Code should be working now. Check out the latest master. Thanks

**Comment by gbtami** [comment]
It's OK now, thx!
